// login 测试
# POST http://47.96.235.211:3000/login/ HTTP/1.1
# content-type: application/json

# {
#     "usr": "admin",
#     "pwd": "123"
# }


POST http://47.96.235.211:3000/publish_assignments/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDA5MTE3MDcsImV4cCI6MTYwMDkxMzUwN30.Od0UyxoVptePIvyy3YuqvzsHXP1JOAzN5zqv6_BiuyI",
    "work_name": "测试1238",
    "work_desc": "描述"
}