### login 测试
POST http://47.96.235.211:3000/login/ HTTP/1.1
content-type: application/json

{
    "usr": "user",
    "pwd": "000"
}

### login 测试
POST http://47.96.235.211:3000/login/ HTTP/1.1
content-type: application/json

{
    "usr": "admin",
    "pwd": "123"
}


### 发布作业测试
POST http://47.96.235.211:3000/publish_assignments/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDEyOTQ0OTEsImV4cCI6MTYwMTI5NjI5MX0.o3CzIpHVivndDacvmhw5w203dHNXsAznRemp5VTwVwE",
    "work_name": "第二次作业",
    "work_desc": "作业具体描述，巴拉巴拉巴拉"
}

### 删除发布的作业测试
POST http://47.96.235.211:3000/delete_assignments/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDEyMjIwOTYsImV4cCI6MTYwMTIyMzg5Nn0.bsIaG3jECe89puPk3HYBDkV_FIstPn4vAeKaXxXoqzA",
    "work_code": "Uo9tRt9hNsvXRMKYEYBdhApak83chA7alPpak9eYB29tRt9hNs9bR6x1kPo8w8c5aRMbk8YmYTsx1oQrx1qQMrb8ZenDZ0nCZ8oC3asCZOoV1"
}

### 上传文件
POST http://47.96.235.211:3000/submit_work/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDExMDA3NDMsImV4cCI6MTYwMTEwMjU0M30.ZMoRT-I5scCWJaBqZIr4Cy2GResn5tx2e8GyKP7d3K0",
    "work_code": "Uo9tRt9hNsvXRMKYEYBdhApak83chA7alPpak9eYB29tRt9hNs9bR6x1kPo8w8c5aRMbk8YmYTsx1oQrx1qQMrb8ZenDZ0nC3avCpWmEJOsV1"
}

### 下载文件
POST http://47.96.235.211:3000/download_assignments/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDExMDUzNjksImV4cCI6MTYwMTEwNzE2OX0.jKTCTOd4o2dF6iCYkne-tc4yXKFSvtVw5G2Zq2ijCSA",
    "work_code": "Uo9tRt9hNsvXRMKYEYBdhApak83chA7alPpak9eYB29tRt9hNs9bR6x1kPo8w8c5aRMbk8YmYTsx1oQrx1qQMrb8ZenDZ0nCJ0mDpWnEJOtV1"
}


### 获取已发布的作业列表
POST http://47.96.235.211:3000/get_published_assignments_list/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDEyOTQ1MjUsImV4cCI6MTYwMTI5NjMyNX0.bZvzkqwJpg0N1vHqYn-cwCMJADrFzMdN1UbmKqwJ61Q",
    "work_code": "Uo9tRt9hNsvXRMKYEYBdhApak83chA7alPpak9eYB29tRt9hNs9bR6x1kPo8w8c5aRMbk8YmYTsx1oQrx1qQMrb8ZenDZ0nCJ0mDpWnEJOtV1"
}


### 获取详细作业信息
POST http://47.96.235.211:300/get_assignments_detail/ HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsInB3ZCI6IjEyMyIsImlkZW50aWZ5IjowLCJpYXQiOjE2MDEyOTQ1OTQsImV4cCI6MTYwMTI5NjM5NH0.ZtINrD1NpWy_UNWnO64RIySqi2ZuUXalnN_kGG0OVjo",
    "work_code": "Uo9tRt9hNsvXRMKYEYBdhApakepchA7alPpak9eYB29tRt9hNs9bR6x1kPo8w8c5aRMbk8YmYTsx1oQrx1qQMrb8ZenDZ0nCZaqDJ4uE34nV1"
}